export type Term = { term: string; plain: string; unit?: string; tag: 'Concept' | 'Skill' | 'Playbook' | 'Cursor' | 'Git' | 'Principle' }

export const GLOSSARY: Term[] = [
  { term: 'Agent', tag: 'Concept', unit: 'foundations', plain: 'An AI that takes actions in a loop: reads files, runs commands, edits code, checks results.' },
  { term: 'Subagent', tag: 'Concept', unit: 'foundations', plain: 'A helper agent spawned by your agent to handle a slice of work, often in parallel.' },
  { term: 'Skill', tag: 'Concept', unit: 'foundations', plain: 'A SKILL.md file of plain-English instructions that teaches an agent one kind of job.' },
  { term: 'Frontmatter', tag: 'Concept', unit: 'foundations', plain: 'The small header between --- lines at the top of a SKILL.md, with name and description.' },
  { term: 'Rule (.mdc)', tag: 'Cursor', unit: 'setup', plain: 'Instructions Cursor can apply to every chat automatically. pstack writes pstack-models.mdc.' },
  { term: 'Plugin', tag: 'Cursor', unit: 'foundations', plain: 'An installable bundle of skills and agents. pstack is one. Install with /add-plugin pstack.' },
  { term: 'Slash command', tag: 'Cursor', unit: 'foundations', plain: 'Typing /name in Cursor chat to load a skill, like /poteto-mode or /how.' },
  { term: 'MCP server', tag: 'Cursor', unit: 'understand', plain: 'A connector that gives agents tools for an outside system: an issue tracker, chat, logs, etc. /why discovers them at run time.' },
  { term: 'Slop', tag: 'Concept', unit: 'foundations', plain: 'Padded, low-quality AI output that looks finished but is not proven or necessary.' },
  { term: 'Fearless parallelism', tag: 'Concept', unit: 'foundations', plain: 'Running many agents at once, safely, because each one verifies its own work.' },
  { term: 'Role', tag: 'Concept', unit: 'setup', plain: 'A job pstack gives to a model, like "bug-fix" or "judgment and prose". Set in /setup-pstack.' },
  { term: 'Panel', tag: 'Concept', unit: 'setup', plain: 'A role whose value is a list of models. One subagent runs per entry.' },
  { term: 'inherit-parent / auto', tag: 'Concept', unit: 'setup', plain: 'Role values meaning "use the parent chat\'s model". Not real model names.' },
  { term: 'Reasoning budget', tag: 'Concept', unit: 'setup', plain: 'How much model "thinking effort" to pay for: unlimited, large, medium or small.' },
  { term: 'Playbook', tag: 'Concept', unit: 'poteto-mode', plain: 'A short numbered checklist for one type of job. poteto-mode has 23.' },
  { term: '/poteto-mode', tag: 'Skill', unit: 'poteto-mode', plain: 'The front door. Matches your task to a playbook and runs the other skills as needed. Sticky.' },
  { term: 'Sticky mode', tag: 'Concept', unit: 'poteto-mode', plain: 'Once started, poteto-mode stays on for the conversation until you opt out.' },
  { term: 'figure-it-out', tag: 'Skill', unit: 'poteto-mode', plain: 'Designs a custom, auditable playbook for big work or when nothing else fits.' },
  { term: 'Worktree', tag: 'Git', unit: 'poteto-mode', plain: 'A second checkout of the same repo in another folder on its own branch. Keeps parallel agents apart.' },
  { term: 'Stack', tag: 'Git', unit: 'verify', plain: 'A chain of PRs where each builds on the one below.' },
  { term: 'Merge-ready', tag: 'Git', unit: 'verify', plain: 'Conflicts, reviews and CI are all clear. Babysit stops here.' },
  { term: '/how', tag: 'Skill', unit: 'understand', plain: 'Explains what code does now, like a senior engineer onboarding you.' },
  { term: '/why', tag: 'Skill', unit: 'understand', plain: 'Digs up why code is shaped this way, from git and other evidence, with citations.' },
  { term: '/teach', tag: 'Skill', unit: 'understand', plain: 'Runs /how and /why and weaves one plain explanation, diagram by diagram.' },
  { term: '/recall', tag: 'Skill', unit: 'understand', plain: 'Rebuilds your own recent context on a topic from your chats and the shared record.' },
  { term: '/architect', tag: 'Skill', unit: 'design', plain: 'Settles types, signatures and module shape before code, via competing sketches.' },
  { term: '/arena', tag: 'Skill', unit: 'design', plain: 'N parallel attempts at the same brief, a judge, pick a base, graft the best parts.' },
  { term: '/swarm', tag: 'Skill', unit: 'design', plain: 'N workers across different slices, each reports PASS/ISSUES/BLOCKED, one report.' },
  { term: '/interrogate', tag: 'Skill', unit: 'design', plain: 'Several models try to break a diff. Findings sorted into Act on, Consider, Noted, Dismissed.' },
  { term: '/tdd', tag: 'Skill', unit: 'build', plain: 'Write the smallest failing test first, then the fix, then rerun. Only when the test is cheap.' },
  { term: '/unslop', tag: 'Skill', unit: 'build', plain: 'Removes AI tells from prose: fancy words, em dashes, filler, chatbot phrases.' },
  { term: '/no-comments', tag: 'Skill', unit: 'build', plain: 'Spawns Comment Sicko to review comments with fresh eyes and remove most of them.' },
  { term: 'Comment Sicko', tag: 'Concept', unit: 'build', plain: 'A read-only, comment-hating reviewer agent with a short keep list.' },
  { term: '/deslop', tag: 'Skill', unit: 'build', plain: 'Cleans slop out of code. Ships in cursor-team-kit, not pstack.' },
  { term: '/blast-radius', tag: 'Skill', unit: 'verify', plain: 'Finds what a small change could break elsewhere and proves its safety by running code.' },
  { term: 'Verification skill', tag: 'Concept', unit: 'verify', plain: 'A project skill (verify-<app>) that teaches agents to drive your app like a user and capture evidence.' },
  { term: 'Feature map', tag: 'Concept', unit: 'verify', plain: 'Part of a verification skill: one file per feature saying what result proves it works.' },
  { term: 'Babysit', tag: 'Playbook', unit: 'verify', plain: 'Drives a PR to merge-ready: conflicts, then threads, then CI. Never merges.' },
  { term: 'Shipping', tag: 'Playbook', unit: 'verify', plain: 'Verifies each PR independently and lands the contiguous verified run from the bottom.' },
  { term: '/loop', tag: 'Cursor', unit: 'overnight', plain: "Cursor's built-in wake mechanism. Re-checks a finish condition on events or a heartbeat." },
  { term: 'Finish condition', tag: 'Concept', unit: 'overnight', plain: 'A check that can pass or fail, like "zero old callers". Not a duration.' },
  { term: 'Decision log', tag: 'Concept', unit: 'overnight', plain: 'A TSV file, one row per decision: ts, phase, decision, why, evidence, result.' },
  { term: '/show-me-your-work', tag: 'Skill', unit: 'overnight', plain: 'Keeps the decision log and summarizes a run with an Attention section.' },
  { term: 'Autopilot-full', tag: 'Playbook', unit: 'overnight', plain: 'Runs a queue of independent PRs to merged, one owner per PR.' },
  { term: 'Autopilot-stack', tag: 'Playbook', unit: 'overnight', plain: 'Builds and verifies one linear stack for you to land yourself.' },
  { term: 'Orchestrate', tag: 'Playbook', unit: 'overnight', plain: 'A multi-day program run by a coordinator chat that never writes code itself.' },
  { term: 'Principle', tag: 'Principle', unit: 'principles', plain: 'One of 23 short rules. Use their names to steer an agent mid-task.' },
  { term: '/automate-me', tag: 'Skill', unit: 'make-it-yours', plain: 'Drafts your own -mode skill from how you actually worked.' },
  { term: '/reflect', tag: 'Skill', unit: 'make-it-yours', plain: 'Three reviewers read a session and propose skill edits for you to approve.' },
  { term: 'Eval', tag: 'Playbook', unit: 'make-it-yours', plain: 'Blind experiment to test a skill change. Defeats the observer effect.' },
  { term: 'Observer effect', tag: 'Concept', unit: 'make-it-yours', plain: 'Agents behave differently when they know they are being evaluated.' },
  { term: '/technical-writing', tag: 'Skill', unit: 'make-it-yours', plain: 'Layered writing standard so a tired engineer understands docs on the first read.' },
  { term: 'benny', tag: 'Concept', unit: 'make-it-yours', plain: 'A dormant automation pack that triages Slack bug reports and reproduces confirmed bugs.' },
  { term: '/bro', tag: 'Skill', unit: 'capstone', plain: 'Restates the last message in plain human language.' },
  { term: '/setup-pstack', tag: 'Skill', unit: 'setup', plain: 'Detects your models, asks for a budget, and writes the per-role model rule.' },
  { term: '/create-verification-skill', tag: 'Skill', unit: 'verify', plain: 'Generates a project-local verify skill by interviewing the repo.' },
]
