export type PrincipleCategory = 'Core' | 'Architecture' | 'Verification' | 'Delegation' | 'Meta'

export type Principle = {
  id: string
  name: string
  category: PrincipleCategory
  plain: string
  when: string
  example: string
  steer: string
}

export const PRINCIPLES: Principle[] = [
  {
    id: 'laziness-protocol',
    name: 'Laziness Protocol',
    category: 'Core',
    plain: 'Get the most result from the least code. Prefer deleting things. Make the smallest change that solves the problem.',
    when: 'Refactoring, sizing a diff, or tempted to add a new layer or abstraction.',
    example: 'Instead of adding a config option, a helper and a wrapper, you change one line that removes the bug.',
    steer: 'apply laziness protocol. what is the smallest diff that fixes this?',
  },
  {
    id: 'foundational-thinking',
    name: 'Foundational Thinking',
    category: 'Core',
    plain: 'Pick the data shape before writing logic. Good data structures make the rest of the code obvious.',
    when: 'Before writing logic, and when deciding what to build first.',
    example: 'You define a `Job` type with clear states before writing the code that runs jobs.',
    steer: 'foundational thinking first. name the data shape before any logic.',
  },
  {
    id: 'redesign-from-first-principles',
    name: 'Redesign from First Principles',
    category: 'Core',
    plain: 'When a new requirement arrives, design as if it had been there from day one. Do not bolt it on.',
    when: 'Fitting a new requirement into an existing design.',
    example: 'Multi-currency support changes the core `Price` type, rather than adding a `currency` flag checked in 40 places.',
    steer: 'redesign from first principles. what would we build if this was always a requirement?',
  },
  {
    id: 'attack-the-premise',
    name: 'Attack the Premise',
    category: 'Core',
    plain: 'If two fixes built on the same assumption both failed, the assumption is probably wrong. Question it before fix number three.',
    when: 'Two or more fixes that share one premise have failed the same check.',
    example: 'Two "add more retries" fixes failed. You count which servers fail and find one always gets the heavy role.',
    steer: 'attack the premise. write down what both failed fixes assumed.',
  },
  {
    id: 'subtract-before-you-add',
    name: 'Subtract Before You Add',
    category: 'Core',
    plain: 'Remove dead code and junk first. Then build on the simpler base.',
    when: 'Planning an addition, refactor, or rewrite.',
    example: 'Delete the three unused adapters before designing the new one.',
    steer: 'subtract before you add. delete the obsolete adapters first.',
  },
  {
    id: 'minimize-reader-load',
    name: 'Minimize Reader Load',
    category: 'Core',
    plain: 'Code is read far more than written. Cut the layers and hidden state a reader has to hold in their head.',
    when: 'Reviewing or shaping code that is hard to follow.',
    example: 'A wrapper with one caller gets inlined so readers stop jumping between files.',
    steer: 'minimize reader load. can a new reader find where X comes from in 30 seconds?',
  },
  {
    id: 'outcome-oriented-execution',
    name: 'Outcome-Oriented Execution',
    category: 'Core',
    plain: 'In a planned rewrite, aim straight at the final design. Do not build throwaway compatibility code just to keep every middle step pretty.',
    when: 'Planned rewrites and migrations with clear phases.',
    example: 'A migration accepts a planned, short breakage in phase 2 instead of writing a temporary shim that lives forever.',
    steer: 'outcome-oriented execution. converge on the target, skip the compatibility shim.',
  },
  {
    id: 'experience-first',
    name: 'Experience First',
    category: 'Core',
    plain: 'When convenience for the builder fights delight for the user, choose the user. Ship fewer, more polished things.',
    when: 'Product, UX, or scope tradeoffs.',
    example: 'You cut two half-done settings to make the main flow feel great.',
    steer: 'experience first. what does the person using this actually notice?',
  },
  {
    id: 'exhaust-the-design-space',
    name: 'Exhaust the Design Space',
    category: 'Core',
    plain: 'When there is no precedent, build 2 or 3 genuinely different prototypes and compare them before committing.',
    when: 'A brand-new interaction or architecture decision with no example to copy.',
    example: 'You sketch a modal, an inline panel and a command palette before picking one.',
    steer: 'exhaust the design space. give me three different sketches first.',
  },
  {
    id: 'build-the-lever',
    name: 'Build the Lever',
    category: 'Core',
    plain: 'For non-trivial work, build the script or tool that does or proves the work. A reviewer can rerun the tool instead of trusting you.',
    when: 'Any non-trivial edit, migration, analysis or check.',
    example: 'You write a codemod that renames 300 call sites, rather than editing them by hand.',
    steer: 'build the lever. write a script that does this and that a reviewer can rerun.',
  },
  {
    id: 'model-the-domain',
    name: 'Model the Domain',
    category: 'Architecture',
    plain: 'Put the real-world rules into one structure (a state machine, a typed model, a lookup table) instead of scattered if/else checks.',
    when: 'Stateful logic, or code that branches a lot or repeats the same assumption.',
    example: 'An order uses one `status` state machine instead of `isPaid`, `isShipped` and `isCancelled` booleans.',
    steer: 'model the domain. replace these booleans with a state machine.',
  },
  {
    id: 'boundary-discipline',
    name: 'Boundary Discipline',
    category: 'Architecture',
    plain: 'Check and clean data where it enters your system (CLI args, config, network). Inside, trust your types.',
    when: 'Wiring validation, error handling, or framework adapters.',
    example: 'You parse the API response once at the edge, then pass typed data inward with no repeated null checks.',
    steer: 'boundary discipline. validate at the edge and delete the inner null checks.',
  },
  {
    id: 'type-system-discipline',
    name: 'Type System Discipline',
    category: 'Architecture',
    plain: 'Make illegal states impossible to even write down. Let the compiler catch mistakes for you.',
    when: 'Designing types or a function signature.',
    example: 'A `Loading | Loaded(data) | Failed(error)` union instead of `data` plus `error` plus `loading` that can disagree.',
    steer: 'type system discipline. make the illegal state unrepresentable.',
  },
  {
    id: 'make-operations-idempotent',
    name: 'Make Operations Idempotent',
    category: 'Architecture',
    plain: 'Running an operation twice, or after a crash halfway, should end in the same correct state.',
    when: 'Commands, startup steps, or loops that run amid crashes and retries.',
    example: 'A sync job checks what already exists before writing, so a retry never makes duplicates.',
    steer: 'make it idempotent. what happens if this runs twice?',
  },
  {
    id: 'migrate-callers-then-delete-legacy-apis',
    name: 'Migrate Callers Then Delete Legacy APIs',
    category: 'Architecture',
    plain: 'When a new internal API replaces an old one, move every caller over and delete the old one in the same wave.',
    when: 'Introducing a new internal API while old callers still exist.',
    example: 'You switch all 12 callers to `fetchUser` and delete `getUserLegacy` in the same PR stack.',
    steer: 'migrate callers then delete the legacy api. no compatibility layer.',
  },
  {
    id: 'separate-before-serializing-shared-state',
    name: 'Separate Before Serializing Shared State',
    category: 'Architecture',
    plain: 'If two workers might write the same thing, first try giving each its own thing. Only add locks when sharing is truly required.',
    when: 'Concurrent actors might write the same file, branch, key, or object.',
    example: 'Each parallel agent gets its own git worktree instead of sharing one folder with a lock.',
    steer: 'separate before serializing shared state. own worktree per attempt, no locks.',
  },
  {
    id: 'prove-it-works',
    name: 'Prove It Works',
    category: 'Verification',
    plain: 'Before saying "done", check the real thing. Run the feature, read the real value. "It compiles" is not proof.',
    when: 'After finishing a task, before declaring success.',
    example: 'You run the import and show the rows it wrote, rather than pointing at a green build.',
    steer: 'apply prove it works. show me the real output, not the build log.',
  },
  {
    id: 'fix-root-causes',
    name: 'Fix Root Causes',
    category: 'Verification',
    plain: 'Reproduce the bug, then keep asking "why?" until you reach the real cause. Fix it there, not where it shows up.',
    when: 'Debugging.',
    example: 'Instead of adding a null check that hides a crash, you find why the value was null.',
    steer: 'fix the root cause. reproduce first, no guard clauses.',
  },
  {
    id: 'sequence-verifiable-units',
    name: 'Sequence Work into Verifiable Units',
    category: 'Verification',
    plain: 'Break big work into small steps that each end in a check. Do not start the next step until the current one is green.',
    when: 'Sweeps, migrations, runs of similar edits, and how you stack commits.',
    example: 'Commit 1 adds the failing test. Commit 2 adds the fix. A reviewer watches it go red, then green.',
    steer: 'sequence into verifiable units. failing test first, then the fix.',
  },
  {
    id: 'test-behavior-not-implementation',
    name: 'Test Behavior, Not Implementation',
    category: 'Verification',
    plain: 'Call code the way users do and check the result against a literal expected value. If a test would pass even when every function returned undefined, it is useless.',
    when: 'Writing, changing, or keeping a test.',
    example: '`expect(total(cart)).toBe(42)` instead of "expect calculateTax to have been called".',
    steer: 'test behavior, not implementation. assert the real output.',
  },
  {
    id: 'guard-the-context-window',
    name: 'Guard the Context Window',
    category: 'Delegation',
    plain: "An agent's memory per chat is limited. Send bulky reading to helper agents and keep only short summaries in the main chat.",
    when: 'Large outputs, long files, repeated reads, fan-out planning.',
    example: 'A subagent reads 40 log files and reports back a 5-line summary.',
    steer: 'guard the context window. send that to a subagent and give me the summary.',
  },
  {
    id: 'never-block-on-the-human',
    name: 'Never Block on the Human',
    category: 'Delegation',
    plain: 'On reversible work, do not stop to ask "should I?". Do it, show the result, and let the human correct course. Still ask before irreversible actions.',
    when: 'Tempted to ask permission for something easy to undo.',
    example: 'The agent writes the code and shows the diff, rather than waiting for "ok, go ahead".',
    steer: 'never block on the human. proceed and show me after.',
  },
  {
    id: 'encode-lessons-in-structure',
    name: 'Encode Lessons in Structure',
    category: 'Meta',
    plain: 'If you have given the same instruction twice, turn it into a lint rule, a check, or a script so nobody has to remember it.',
    when: 'You catch yourself repeating the same correction.',
    example: 'A lint rule bans the old import, instead of a README line asking people not to use it.',
    steer: 'encode the lesson in structure. make it a lint, not a reminder.',
  },
]

export const PRINCIPLE_CATEGORIES: { id: PrincipleCategory; blurb: string; hue: number }[] = [
  { id: 'Core', blurb: 'How much to build and when to rethink.', hue: 30 },
  { id: 'Architecture', blurb: 'Where state, validation and compatibility live.', hue: 200 },
  { id: 'Verification', blurb: 'What counts as proof.', hue: 140 },
  { id: 'Delegation', blurb: 'Keeping parallel work sane.', hue: 270 },
  { id: 'Meta', blurb: 'Turning lessons into rules.', hue: 330 },
]
